parser: babel-eslint
ecmaVersion: 8
ecmaFeatures:
  experimentalObjectRestSpread: true
  jsx: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
plugins:
  - react
env:
  browser: true
  node: true
rules:
  no-extra-parens:
    - 0
    - all
  no-template-curly-in-string: error
  no-unsafe-negation: warn
  accessor-pairs: error
  array-callback-return: error
  consistent-return: error
  curly: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq:
    - error
    - smart
  no-alert: error
  no-div-regex: error
  no-else-return: error
  no-eval: error
  no-extra-bind: error
  no-labels: error
  no-fallthrough: warn
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: error
  no-multi-spaces: error
  no-multi-str: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-param-reassign: error
  no-return-assign: error
  no-return-await: error
  no-self-compare: error
  no-unmodified-loop-condition: error
  no-throw-literal: error
  no-unused-expressions:
    - error
    - allowTernary: true
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: warn
  no-useless-return: error
  no-void: error
  no-with: error
  require-await: warn
  vars-on-top: error
  no-warning-comments: warn
  yoda:
    - error
    - never
    - onlyEquality: true
  no-use-before-define: error
  array-bracket-spacing:
    - error
    - never
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - stroustrup
  camelcase:
    - error
    - properties: always
  comma-dangle:
    - error
    - only-multiline: true
  comma-spacing: error
  computed-property-spacing:
    - error
    - never
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-name-matching:
    - error
    - always
  func-style:
    - error
    - expression
  indent:
    - warn
    - 2
    - VariableDeclarator:
        var: 2
        let: 2
        const: 3
  jsx-quotes:
    - error
    - prefer-double
  key-spacing: error
  keyword-spacing:
    - error
    - before: true
      after: true
  line-comment-position:
    - warn
    - position: above
  linebreak-style:
    - error
    - unix
  max-nested-callbacks:
    - error
    - max: 3
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  no-inline-comments: warn
  no-lonely-if: error
  no-nested-ternary: error
  no-tabs: error
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - always
  object-property-newline: error
  one-var-declaration-per-line:
    - error
    - initializations
  one-var:
    - warn
    - always
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_$"
      varsIgnorePattern: "^_$"
      caughtErrorsIgnorePattern: "^_$"
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - consistent-as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-function-paren:
    - error
    - always
  space-in-parens:
    - error
    - never
  spaced-comment:
    - error
    - always
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  generator-star-spacing:
    - error
    - before: true
      after: false
  no-confusing-arrow: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-const: error
  prefer-destructuring: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  yield-star-spacing:
    - error
    - before
  template-curly-spacing: error
  no-console:
    - warn
